### ISSUE TITLE
Go mod dependency issue

### ISSUE THREAD

**Issue by curio77** [aletheia-icu/broccoli#1]
In the course of trying this (with Go v1.14.2), I encountered the following error running `go mod tidy` after adding broccoli as a dependency (via a side-effect-only tool import, `import _ "aletheia.icu/broccoli"`):

```
go: finding module for package aletheia.icu/broccoli
go: downloading aletheia.icu/broccoli v1.0.0-beta
go: found aletheia.icu/broccoli in aletheia.icu/broccoli v1.0.0-beta
go: aletheia.icu/broccoli@v1.0.0-beta requires
        aletheia.icu/broccoli/fs@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by tucnak** [comment]
Does [the latest commit](https://github.com/aletheia-icu/broccoli/commit/d66f665d36d3e1f330864f2a14475b327accd4e2) fix it? I removed the replace directive altogether, as `fs` can be relied upon already.

**Comment by curio77** [comment]
Thanks for the quick response, but apparently not. In fact, `go get -u aletheia.icu/broccoli` suffices to trigger the same error.

**Comment by tucnak** [comment]
@curio77 apparently, this has to do with cache or something, force-pushing `v1.0.0-beta` tag was not a good idea. I was forced to relese `v1.0.1`, but evidently (on a clean machine with go1.14) it does work. 

Please try `go get -u aletheia.icu/broccoli@v1.0.1` and confirm whether if this is resolved.

**Comment by curio77** [comment]
It now works, even without the version suffix. FWIW, I did do an intermediate `go clean -modcache` just to be sure, but that had no effect prior to the version bump you now did.  Anyway, thanks for resolving this! :-)
