### ISSUE TITLE
File size seems bigger than packr

### ISSUE THREAD

**Issue by amir20** [aletheia-icu/broccoli#4]
Hello, 

We chatted a little on Reddit. I wanted to use what you had so far and see how much smaller is the output. 

I have a project called [Dozzle](https://github.com/amir20/dozzle). I compared the output with what I currently have with `packr` and the binary is actually _bigger_. 

See below:

<img width="645" alt="Screen Shot 2020-04-16 at 10 07 48 AM" src="https://user-images.githubusercontent.com/260667/79485475-2b039d80-7fca-11ea-9dad-2a6fc3aa14ab.png">

I have pushed my branch to [broccoli](https://github.com/amir20/dozzle/tree/broccoli).  Not sure what I am doing wrong. You can run `yarn build` to get a static folder that is the source.

**Comment by demget** [comment]
It seems you didn't remove packr from binary dependencies. Try to fully rewrite your logic for broccoli. Actually I already tried some, take a look:
![](https://i.imgur.com/hGUILa0.png)

**Comment by amir20** [comment]
@demget I don't think I need to remove packr. My screenshot shows two files. `assets.gen.go` is generated by broccoli using `go generate`. It is embedding all files in `./static`. The other file `a_main-packr.go` is generated using `packr -d`. 

There are no binary dependencies. It's purely the assets being compiled to a go file. `assets.gen.go` should be smaller than `a_main-packr.go`.

**Comment by amir20** [comment]
After looking at the generated file, I believe Broccoli has a bug. Packr generates a string for each asset. For example, my favicon looks like the following in `packr`. 

```
"\"H4sIAAAAAAAA/+x9eXhbxdX3kZdYlq3FsmJbul60WLEWJ17ifZO8SnECCQlxEuOQxQmBsHdjKYGQhkBZC4EkrC1taWkLBUpLoBTK0lKWFmhL2VPCEiCNXimhvM/TP97n6/fcTbq6d67uKssW+iWylrkz5/xmzpw5M3NHAtBAIZhM+LMWziwEmAAAu518f78W4OlCgGCQfO+pADjDALBzJ/V+GcCN9QBHjpDvVxwHeOwCAA8AmPBygPycgAagvIR84K/xx8DAQNIj0NMNgZ4eCPT2wkBfHwz0449+COCvB/...
```

However, in Broccoli, the generated file looks like...

```
[]byte("\xab\vY\t\r\xff\x83\x02\x01\x02\xff\x84\x00\x01\xff\x82\x00\x00=\xff\x81\x03\x01\x02\xff\x82\x00\x01\x05\x01\x04Data\x01\n\x00\x01\x05Fpath\x01\f\x00\x01\x05Fname\x01\f\x00\x01\x05Fsize\x01\x04\x00\x01\x05Ftime\x01\x04\x00\x00\x00\xfd\x02\xb1\xc8\xff\x84\x00\a\x02\x06static\x01\x06static\x01\xfe\x02\x00\x01\xfc\xbd1\x1e\xf1\x00\x01\xfe\x1a\xcc[\x05aQ¶\xa5ԃ\xf3@\x10\xed\xd2+\x8cH\xb6YG\x81\xa2\xaa^\x12\xb81\x04\xfd\xa7Ye\x882\xe2\xc6\xc0`\t\xa1\x8aZk4\xda$\x06ѥ\xaa\xa3-\xe2I\xde\xefHO\xb0\xc4&:\xd3Zcok\x8b\xb3\xef\xab^\xd9....
```

I am not sure what is going on but seems like Broccoli escapes the bytes. 

Packr doesn't enable compression by default. You need to do `packr -d`.

**Comment by demget** [comment]
@amir20 I'm wondering why do you care about the size of generated file? Broccoli's binary is still smaller than packr's one. We did some benchmarks, with `packr -z` compressed flag as well.

**Comment by amir20** [comment]
You may be right. After removing everything I have

```
.rwxr-xr-x   12Mi amirraminfar primarygroup 16 Apr 12:24   -N dozzle_broccoli
.rwxr-xr-x   13Mi amirraminfar primarygroup 16 Apr 12:25   -N dozzle_packr

```

But only 1MB different. However, it did take an additional 15 seconds for broccoli to process the files. Closing for now! 

There might be an opportunity to save more by figuring out why the output of packr is smaller.
